export const Data = [
  {
    id: 12342,
    firstName: "Ahmad",
    lastName: "Ali",
    age: 20,
    email: "aniterocketni8@gmail.com",
  },
  {
    id: 234141,
    firstName: "Intikhab_Wali",
    lastName: "Khan",
    age: 50,
    email: "bistrorocketni8@gmail.com",
  },
  {
    id: 42154,
    firstName: "Huzaifa",
    lastName: "Suhail",
    age: 23,
    email: "riterocketni8@gmail.com",
  },
  {
    id: 342324,
    firstName: "Anas",
    lastName: "Maqsood",
    age: 40,
    email: "rocketni8@gmail.com",
  },
  {
    id: 987654,
    firstName: "Ayesha",
    lastName: "Hussain",
    age: 28,
    email: "ayesha.hussain@example.com",
  },
  {
    id: 123456,
    firstName: "Zara",
    lastName: "Ahmed",
    age: 32,
    email: "zara.ahmed@example.com",
  },
  {
    id: 789012,
    firstName: "Ali",
    lastName: "Raza",
    age: 45,
    email: "ali.raza@example.com",
  },
  {
    id: 345678,
    firstName: "Fatima",
    lastName: "Sheikh",
    age: 26,
    email: "fatima.sheikh@example.com",
  },
  {
    id: 901234,
    firstName: "Omar",
    lastName: "Farooq",
    age: 37,
    email: "omar.farooq@example.com",
  },
  {
    id: 567890,
    firstName: "Hina",
    lastName: "Kamal",
    age: 29,
    email: "hina.kamal@example.com",
  },
  {
    id: 111222,
    firstName: "Sami",
    lastName: "Khan",
    age: 40,
    email: "sami.khan@example.com",
  },
  {
    id: 333444,
    firstName: "Amna",
    lastName: "Yusuf",
    age: 35,
    email: "amna.yusuf@example.com",
  },
  {
    id: 555666,
    firstName: "Bilal",
    lastName: "Malik",
    age: 22,
    email: "bilal.malik@example.com",
  },
  {
    id: 777888,
    firstName: "Nida",
    lastName: "Aslam",
    age: 31,
    email: "nida.aslam@example.com",
  },
  {
    id: 999000,
    firstName: "Usman",
    lastName: "Shaikh",
    age: 47,
    email: "usman.shaikh@example.com",
  },
  {
    id: 112233,
    firstName: "Sara",
    lastName: "Rehman",
    age: 29,
    email: "sara.rehman@example.com",
  },
  {
    id: 445566,
    firstName: "Hamza",
    lastName: "Iqbal",
    age: 40,
    email: "hamza.iqbal@example.com",
  },
  {
    id: 778899,
    firstName: "Mariam",
    lastName: "Ali",
    age: 23,
    email: "mariam.ali@example.com",
  },
  {
    id: 101010,
    firstName: "Zain",
    lastName: "Hussain",
    age: 38,
    email: "zain.hussain@example.com",
  },
  {
    id: 123989,
    firstName: "Anum",
    lastName: "Naeem",
    age: 27,
    email: "anum.naeem@example.com",
  },
  {
    id: 123129,
    firstName: "Hafsa",
    lastName: "Anoosha",
    age: 27,
    email: "anum.naeem@example.com",
  },
];
